[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn config.wsgi --log-file -"
releaseCommand = "python manage.py migrate --noinput"

[env]
DJANGO_SETTINGS_MODULE = "config.settings.prod"
PYTHON_VERSION = "3.12"