# Generated by Django 5.2.7 on 2025-10-28 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.PositiveIntegerField(help_text='in minutes')),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
